// Code generated by test. DO NOT EDIT.

package test

// GeneratedFunction should trigger warning when generated flag is enabled
func GeneratedFunction() { // want "exported function \"GeneratedFunction\" has no test"
	// generated function
}

// GeneratedFunctionWithTest should not trigger warning when generated flag is enabled
func GeneratedFunctionWithTest() {
	// generated function
}
