// Code generated by some tool. DO NOT EDIT.

package fieldorder

func _() {
	type Person struct {
		Name    string
		Age     int
		Email   string
		Address string
	}

	// This struct literal has fields out of order, but since this is a generated file,
	// the fieldorder analyzer should skip it and NOT report any issues
	_ = Person{
		Age:     30,     // out of order
		Name:    "John", // out of order
		Email:   "john@example.com",
		Address: "123 Main St",
	}

	// Another out-of-order example that should be ignored
	_ = Person{
		Email:   "jane@example.com", // out of order
		Name:    "Jane",             // out of order
		Age:     25,                 // out of order
		Address: "456 Oak Ave",
	}
}
